name: 'GitHub Pages'

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    name: 'Build & Upload'
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'chickensoft-games/setup-godot@v2'
        with:
          version: '4.4.1'
          use-dotnet: false
          include-templates: true
      - run: 'curl --create-dirs -o ~/.local/bin/rcedit.exe "https://github.com/electron/rcedit/releases/download/v2.0.0/rcedit-x64.exe"'
      - run: './bake build-release'
      - uses: 'actions/upload-pages-artifact@v3'
        with:
          path: './Build/Release/website'

  deploy:
    name: 'Deploy'
    runs-on: 'ubuntu-24.04'
    needs: ['build']
    if: ${{ github.ref == 'refs/heads/main' }}
    environment:
      name: 'github-pages'
      url: '${{ steps.deployment.outputs.page_url }}'
    steps:
      - name: 'Deploy to GitHub Pages'
        id: 'deployment'
        uses: 'actions/deploy-pages@v4'
